// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWEpYSLKz3Tt8CGu7nZJ1j4U_-XZs1DY',
    appId: '1:316213209108:web:ba7e78e2cf23bf74ec1f01',
    messagingSenderId: '316213209108',
    projectId: 'musicapp-d17d9',
    authDomain: 'musicapp-d17d9.firebaseapp.com',
    storageBucket: 'musicapp-d17d9.firebasestorage.app',
    measurementId: 'G-EYS3HQNTJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA7MhD3UbQu1fGBIybWY0dvAOHuooJHMg',
    appId: '1:316213209108:android:e83eff56dd4732d0ec1f01',
    messagingSenderId: '316213209108',
    projectId: 'musicapp-d17d9',
    storageBucket: 'musicapp-d17d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk6DVA-OjxgJK6dWPXQtwxyNvXVeE6FD8',
    appId: '1:316213209108:ios:870f0ce6f5d81d18ec1f01',
    messagingSenderId: '316213209108',
    projectId: 'musicapp-d17d9',
    storageBucket: 'musicapp-d17d9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk6DVA-OjxgJK6dWPXQtwxyNvXVeE6FD8',
    appId: '1:316213209108:ios:870f0ce6f5d81d18ec1f01',
    messagingSenderId: '316213209108',
    projectId: 'musicapp-d17d9',
    storageBucket: 'musicapp-d17d9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzWEpYSLKz3Tt8CGu7nZJ1j4U_-XZs1DY',
    appId: '1:316213209108:web:6e4cb2e1f3983baeec1f01',
    messagingSenderId: '316213209108',
    projectId: 'musicapp-d17d9',
    authDomain: 'musicapp-d17d9.firebaseapp.com',
    storageBucket: 'musicapp-d17d9.firebasestorage.app',
    measurementId: 'G-7J45MZVNGG',
  );

}